// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD27v87skueaeXdLdmDLtcnpNZQD0KMmuY',
    appId: '1:401740085300:web:022ff986c5d3b618043261',
    messagingSenderId: '401740085300',
    projectId: 'workoutapp-573b3',
    authDomain: 'workoutapp-573b3.firebaseapp.com',
    storageBucket: 'workoutapp-573b3.appspot.com',
    measurementId: 'G-RDRQ9D6JX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3yTj6Vh7Jw9dcZRA2QYtYXHT2hGafeLc',
    appId: '1:401740085300:android:aae99e6996b37af1043261',
    messagingSenderId: '401740085300',
    projectId: 'workoutapp-573b3',
    storageBucket: 'workoutapp-573b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbk3ldK1_bk4BBAVsqIdCWZUnhvSNBaME',
    appId: '1:401740085300:ios:919c982df1c9d119043261',
    messagingSenderId: '401740085300',
    projectId: 'workoutapp-573b3',
    storageBucket: 'workoutapp-573b3.appspot.com',
    iosBundleId: 'com.wotkoutapp.app',
  );
}
